/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html", "./**/*.cshtml", "./**/*.razor", "./**/*.js"],
  theme: {
    extend: {},
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '-2xl': { 'max': '1535px' },
      '-xl': { 'max': '1279px' },
      '-lg': { 'max': '1023px' },
      '-md': { 'max': '767px' },
      '-sm': { 'max': '639px' }
    }
  },
  plugins: [],
  safelist: [
    "hidden",
    "sm:hidden",
    "md:hidden",
    "lg:hidden",
    "xl:hidden",
    "2xl:hidden",
    "block",
    "sm:block",
    "md:block",
    "lg:block",
    "xl:block",
    "2xl:block",
    "sm:w-auto",
    "flex",
    "sm:flex",
    "md:flex",
    "lg:flex",
    "xl:flex",
    "2xl:flex",
    "space-x-4",
    "sm:space-x-4",
    "md:space-x-4",
    "lg:space-x-4",
    "xl:space-x-4",
    "2xl:space-x-4",
    "-space-y-4",
    "-sm:space-y-4",
    "-md:space-y-4",
    "-lg:space-y-4",
    "-xl:space-y-4",
    "-2xl:space-y-4",
    "bg-red-500",
    "bg-orange-500",
    "bg-yellow-500",
    "bg-lime-500",
    "bg-green-500",
    "bg-cyan-500",
    "bg-blue-500",
    "bg-violet-500",
    "bg-purple-500",
    "bg-pink-500",
    "outline-red-500",
    "outline-orange-500",
    "outline-yellow-500",
    "outline-lime-500",
    "outline-green-500",
    "outline-cyan-500",
    "outline-blue-500",
    "outline-violet-500",
    "outline-purple-500",
    "outline-pink-500",
    "dark:bg-red-900",
    "dark:bg-orange-900",
    "dark:bg-yellow-900",
    "dark:bg-lime-900",
    "dark:bg-green-900",
    "dark:bg-cyan-900",
    "dark:bg-blue-900",
    "dark:bg-violet-900",
    "dark:bg-purple-900",
    "dark:bg-pink-900",
    "dark:outline-red-900",
    "dark:outline-orange-900",
    "dark:outline-yellow-900",
    "dark:outline-lime-900",
    "dark:outline-green-900",
    "dark:outline-cyan-900",
    "dark:outline-blue-900",
    "dark:outline-violet-900",
    "dark:outline-purple-900",
    "dark:outline-pink-900",
    "bg-red-200",
    "bg-orange-200",
    "bg-yellow-200",
    "bg-lime-200",
    "bg-green-200",
    "bg-cyan-200",
    "bg-blue-200",
    "bg-violet-200",
    "bg-purple-200",
    "bg-pink-200",
    "outline-red-200",
    "outline-orange-200",
    "outline-yellow-200",
    "outline-lime-200",
    "outline-green-200",
    "outline-cyan-200",
    "outline-blue-200",
    "outline-violet-200",
    "outline-purple-200",
    "outline-pink-200"
  ],
  future: {
    hoverOnlyWhenSupported: true,
  }
}
